- hosts: all
  tasks:
    - name: Include vars of vars.yaml
      ansible.builtin.include_vars:
        file: ./vars.yaml
      tags:
        - always

    - name: Import core tasks
      ansible.builtin.import_tasks: ./tasks/core.yaml

    - name: Import git tasks
      ansible.builtin.import_tasks: ./tasks/git.yaml

    - name: Import oh-my-zsh tasks
      ansible.builtin.import_tasks: ./tasks/oh-my-zsh.yaml

    - name: Import stow tasks
      ansible.builtin.import_tasks: ./tasks/stow.yaml

    - name: Import starship tasks
      ansible.builtin.import_tasks: ./tasks/starship.yaml

    - name: Import neovim tasks
      ansible.builtin.import_tasks: ./tasks/neovim.yaml

    - name: Import devtools tasks
      ansible.builtin.import_tasks: ./tasks/devtools.yaml

    - name: Import termshark tasks
      ansible.builtin.import_tasks: ./tasks/termshark.yaml

    - name: Import go tasks
      ansible.builtin.import_tasks: ./tasks/go.yaml

    - name: Import rust tasks
      ansible.builtin.import_tasks: ./tasks/rust.yaml
