- hosts: all
  tasks:
    - name: Include vars of vars.yaml
      ansible.builtin.include_vars:
        file: ./vars.yaml
      tags:
        - always

    - name: Import core tasks
      ansible.builtin.import_tasks: ./tasks/core.yaml

    - name: Import git tasks
      ansible.builtin.import_tasks: ./tasks/git.yaml

    - name: Import zsh
      ansible.builtin.import_tasks: ./tasks/zsh.yaml

    - name: Import stow tasks
      ansible.builtin.import_tasks: ./tasks/stow.yaml

    - name: Import starship tasks
      ansible.builtin.import_tasks: ./tasks/starship.yaml

    - name: Import neovim tasks
      ansible.builtin.import_tasks: ./tasks/neovim.yaml

    - name: Import devtools tasks
      ansible.builtin.import_tasks: ./tasks/devtools.yaml

    - name: Import termshark tasks
      ansible.builtin.import_tasks: ./tasks/termshark.yaml

    - name: Import go tasks
      ansible.builtin.import_tasks: ./tasks/go.yaml

    - name: Import cpp tasks
      ansible.builtin.import_tasks: ./tasks/cpp.yaml

    - name: Import python tasks
      ansible.builtin.import_tasks: ./tasks/python.yaml

    - name: Import rust tasks
      ansible.builtin.import_tasks: ./tasks/rust.yaml

    - name: Import nodejs tasks
      ansible.builtin.import_tasks: ./tasks/nodejs.yaml

    - name: Import circleci tasks
      ansible.builtin.import_tasks: ./tasks/circleci.yaml

    - name: Import hugo tasks
      ansible.builtin.import_tasks: ./tasks/hugo.yaml

    - name: Import aws tasks
      ansible.builtin.import_tasks: ./tasks/aws.yaml
      
    - name: Import glow tasks
      ansible.builtin.import_tasks: ./tasks/glow.yaml

    - name: Import notes tasks
      ansible.builtin.import_tasks: ./tasks/notes.yaml

    - name: Import dagger tasks
      ansible.builtin.import_tasks: ./tasks/dagger.yaml

    - name: Import docker tasks
      ansible.builtin.import_tasks: ./tasks/docker.yaml

    - name: Import yazi tasks
      ansible.builtin.import_tasks: ./tasks/yazi.yaml
    #     - name: Import harlequin tasks
    #       ansible.builtin.import_tasks: ./tasks/harlequin.yaml
