- hosts: localhost
  # pre_tasks:
  #   - name: Update all Debian/Ubuntu packages to their latest version
  #     ansible.builtin.apt:
  #       update_cache: true
  #       cache_valid_time: 3600
  #       name: "*"
  #       state: present
  #     tags:
  #       - core
  #       - fonts
  #       - git
  #       - neovim
  #       - nodejs
  #       - starship
  #       - stow
  #       - zsh
  #     become: true

  tasks:
    - name: Include vars of vars.yaml
      ansible.builtin.include_vars:
        file: ./vars.yaml
      tags:
        - core
        - devtools
        - fonts
        - git
        - neovim
        - nodejs
        - starship
        - stow
        - zsh

    - name: Run core tasks
      ansible.builtin.include_tasks:
        file: ./tasks/core.yaml
        apply:
          tags:
            - core
      tags:
        - core

    - name: Run git tasks
      ansible.builtin.include_tasks:
        file: ./tasks/git.yaml
        apply:
          tags:
            - git
      tags:
        - git

    - name: Run zsh tasks
      ansible.builtin.include_tasks:
        file: ./tasks/zsh.yaml
        apply:
          tags:
            - zsh
      tags:
        - zsh

    #   - name: Run fonts tasks
    #     ansible.builtin.include_tasks:
    #       file: ./tasks/fonts.yaml
    #       apply:
    #         tags:
    #           - fonts
    #     tags:
    #       - fonts

    - name: Run stow tasks
      ansible.builtin.include_tasks:
        file: ./tasks/stow.yaml
        apply:
          tags:
            - stow
      tags:
        - stow

    - name: Run starship tasks
      ansible.builtin.include_tasks:
        file: ./tasks/starship.yaml
        apply:
          tags:
            - starship
      tags:
        - starship

    - name: Run neovim tasks
      ansible.builtin.include_tasks:
        file: ./tasks/neovim.yaml
        apply:
          tags:
            - neovim
      tags:
        - neovim

    - name: Run dev tools tasks
      ansible.builtin.include_tasks:
        file: ./tasks/devtools.yaml
        apply:
          tags:
            - devtools
      tags:
        - devtools
  # - name: Run nodejs tasks
  #   ansible.builtin.include_tasks:
  #     file: ./tasks/nodejs.yaml
  #     apply:
  #       tags:
  #         - nodejs
  #   tags:
  #     - nodejs
