- hosts: localhost
  tasks:
    - name: Include vars of vars.yaml
      ansible.builtin.include_vars:
        file: ./vars.yaml
      tags:
        - core
        - devtools
        - fonts
        - git
        - neovim
        - nodejs
        - starship
        - stow
        - termshark
        - zsh
    
    - name: Run included tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop:
        - ./tasks/core.yaml
        - ./tasks/git.yaml
        - ./tasks/zsh.yaml
        - ./tasks/stow.yaml
        - ./tasks/starship.yaml
        - ./tasks/neovim.yaml
        - ./tasks/devtools.yaml
        - ./tasks/termshark.yaml

