- hosts: localhost
  gather_facts: false
  tasks:
    - name: Include vars of vars.yaml
      ansible.builtin.include_vars:
        file: ./vars.yaml
      tags:
        - always

    - name: Import core tasks
      ansible.builtin.import_tasks: ./tasks/core.yaml

    - name: Import git tasks
      ansible.builtin.import_tasks: ./tasks/git.yaml

    - name: Import stow tasks
      ansible.builtin.import_tasks: ./tasks/stow.yaml

    - name: Import tmux tasks
      ansible.builtin.import_tasks: ./tasks/tmux.yaml

    - name: Import programminglanguages tasks
      ansible.builtin.import_tasks: ./tasks/programminglanguages.yaml

    - name: Import devtools tasks
      ansible.builtin.import_tasks: ./tasks/devtools.yaml

    - name: Import zsh tasks
      ansible.builtin.import_tasks: ./tasks/zsh.yaml

    - name: Import neovim tasks
      ansible.builtin.import_tasks: ./tasks/neovim.yaml

    - name: Import notes tasks
      ansible.builtin.import_tasks: ./tasks/notes.yaml

    - name: Import ai tasks
      ansible.builtin.import_tasks: ./tasks/ai.yaml
