- name: Run ai tasks
  tags:
    - ai
  block:
    - name: Install ai dependencies
      community.general.homebrew:
        name:
          - aichat
        state: latest
        update_homebrew: yes

    - name: Install ai cask dependencies
      community.general.homebrew_cask:
        name:
          - claude-code
        state: latest
