- name: Set up aliases
  tags: 
    - aliases
  block:
  - name: Set up aliases
    ansible.builtin.blockinfile:
      state: present
      path: $HOME/.zshrc
      block: |
        alias ps='grc ps'
      marker_begin: "START PS ALIAS" 
      marker_end: "END PS ALIAS"

  - name: Source zsh
    shell: source $HOME/.zshrc
    args:
      executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu

