- name: Run core tasks
  tags:
    - core
  block:
  - name: Install curl
    community.general.homebrew:
      name: curl
      state: present

  - name: Install wget
    community.general.homebrew:
      name: wget
      state: present

  - name: Install tree
    community.general.homebrew:
      name: tree
      state: present

  - name: Install unzip
    community.general.homebrew:
      name: unzip
      state: present

  - name: Install vim
    community.general.homebrew:
      name: vim
      state: present

  - name: Install tmux
    community.general.homebrew:
      name: tmux
      state: present

  - name: Install tmuxinator
    community.general.homebrew:
      name: tmuxinator
      state: present

  - name: Install ack
    community.general.homebrew:
      name: ack
      state: present

