- name: Install man
  ansible.builtin.apt:
    name: man
    state: present

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present

- name: Install wget
  ansible.builtin.apt:
    name: wget
    state: present

- name: Install tree
  ansible.builtin.apt:
    name: tree
    state: present

- name: Install unzip
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present

- name: Install tmux
  ansible.builtin.apt:
    name: tmux
    state: present