---
- name: Run cpp tasks
  tags:
    - cpp
  block:
    - name: Install gcc
      community.general.homebrew:
        name: gcc
        state: latest

    - name: Install cmake
      community.general.homebrew:
        name: cmake
        state: latest

    - name: Install ninja-make
      community.general.homebrew:
        name: ninja
        state: latest
