- name: Run cpp tasks
  tags:
    - cpp
  block:
  - name: Install gcc
    community.general.homebrew:
      name: gcc@14
      state: present

  - name: Install cmake
    community.general.homebrew:
      name: cmake
      state: present

  - name: Install ninja-make
    community.general.homebrew:
      name: ninja
      state: present
