---
- name: Run devops tasks
  tags:
    - devops
  block:
    - name: Install yazi
      community.general.homebrew:
        name: yazi
        state: latest

    - name: Install btop
      community.general.homebrew:
        name: btop
        state: latest

    - name: Install ffmpeg
      community.general.homebrew:
        name: ffmpeg
        state: latest

    - name: Install hashicorp terraform
      ansible.builtin.shell: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform

    - name: Install snyk
      community.general.homebrew:
        name: snyk-cli
        state: latest

    - name: Install syft
      community.general.homebrew:
        name: syft
        state: latest

    - name: Install grype
      community.general.homebrew:
        name: grype
        state: latest

    - name: Install grc
      community.general.homebrew:
        name: grc
        state: latest

    - name: Install lnav
      community.general.homebrew:
        name: lnav
        state: latest

    # - name: Install duckdb
    #   community.general.homebrew:
    #     name: duckdb
    #     state: present

    - name: Install buku
      community.general.homebrew:
        name: buku
        state: latest

    - name: Install zoxide
      community.general.homebrew:
        name: zoxide
        state: latest

    - name: Configure zoxide
      ansible.builtin.blockinfile:
        state: present
        path: $HOME/.zshrc
        block: |
          eval "$(zoxide init zsh)"
        marker_begin: "START ZOXIDE CONFIG"
        marker_end: "END ZOXIDE CONFIG"

    - name: Source zsh
      shell: source $HOME/.zshrc
      args:
        executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu

    - name: Install eza
      community.general.homebrew:
        name: eza
        state: latest

    - name: Configure eza
      ansible.builtin.blockinfile:
        state: present
        path: $HOME/.zshrc
        block: |
          alias e='eza'
        marker_begin: "START EZA CONFIG"
        marker_end: "END EZA CONFIG"

    - name: Source zsh
      shell: source $HOME/.zshrc
      args:
        executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu

    - name: Install bat
      community.general.homebrew:
        name: bat
        state: latest

    - name: Configure bat
      ansible.builtin.blockinfile:
        state: present
        path: $HOME/.zshrc
        block: |
          BAT_THEME=CatppuccinMocha
        marker_begin: "START BAT CONFIG"
        marker_end: "END BAT CONFIG"

    - name: Source zsh
      shell: source $HOME/.zshrc
      args:
        executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu

    - name: Install direnv
      community.general.homebrew:
        name: direnv
        state: latest

    - name: Configure direnv
      ansible.builtin.blockinfile:
        state: present
        path: $HOME/.zshrc
        block: |
          eval "$(direnv hook zsh)"
        marker_begin: "START DIRENV CONFIG"
        marker_end: "END DIRENV CONFIG"

    - name: Source zsh
      shell: source $HOME/.zshrc
      args:
        executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu
