- name: Run devops tasks
  tags:
    - devops
  block:
  - name: Install yazi
    community.general.homebrew:
      name: yazi
      state: present

  - name: Install btop
    community.general.homebrew:
      name: btop
      state: present

  - name: Install ffmpeg
    community.general.homebrew:
      name: ffmpeg
      state: present

  - name: Install hashicorp terraform
    ansible.builtin.shell: |
      brew tap hashicorp/tap
      brew install hashicorp/tap/terraform

  - name: Install snyk
    community.general.homebrew:
      name: snyk-cli
      state: present

  - name: Install syft
    community.general.homebrew:
      name: syft
      state: present

  - name: Install grype
    community.general.homebrew:
      name: grype
      state: present

  - name: Install grc
    community.general.homebrew:
      name: grc
      state: present

  - name: Install lnav
    community.general.homebrew:
      name: lnav
      state: present

  # - name: Install duckdb
  #   community.general.homebrew:
  #     name: duckdb
  #     state: present

  - name: Install buku
    community.general.homebrew:
      name: buku
      state: present

  - name: Install zoxide
    community.general.homebrew:
      name: zoxide
      state: present

  - name: Configure zoxide 
    ansible.builtin.blockinfile:
      state: present
      path: $HOME/.zshrc
      block: |
        eval "$(zoxide init zsh)"
      marker_begin: "START ZOXIDE CONFIG"
      marker_end: "END ZOXIDE CONFIG"

  - name: Source zsh
    shell: source $HOME/.zshrc
    args:
      executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu

  - name: Install eza
    community.general.homebrew:
      name: eza
      state: present

  - name: Configure eza 
    ansible.builtin.blockinfile:
      state: present
      path: $HOME/.zshrc
      block: |
        alias e='eza'
      marker_begin: "START EZA CONFIG"
      marker_end: "END EZA CONFIG"

  - name: Source zsh
    shell: source $HOME/.zshrc
    args:
      executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu

  - name: Install bat
    community.general.homebrew:
      name: bat
      state: present

  - name: Configure bat 
    ansible.builtin.blockinfile:
      state: present
      path: $HOME/.zshrc
      block: |
        BAT_THEME=CatppuccinMocha
      marker_begin: "START BAT CONFIG"
      marker_end: "END BAT CONFIG"

  - name: Source zsh
    shell: source $HOME/.zshrc
    args:
      executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu
