---
- name: Run devtools tasks
  tags:
    - devtools
  block:
    - name: Install useful tools
      community.general.homebrew:
        name:
          - age
          - bat
          - btop
          - buku
          - direnv
          - eza
          - fd
          - fzf
          - ffmpeg
          - glow
          - grc
          - grype
          - go-task
          - lazygit
          - lnav
          - protobuf
          - sshs
          - snyk-cli
          - syft
          - tldr
          - yazi
          - zoxide
        state: latest

    - name: Install hashicorp terraform
      ansible.builtin.shell: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/terraform
