- name: Run devtools tasks
  tags:
    - devtools
  block:
    - name: Install useful tools using homebrew cask
      community.general.homebrew_cask:
        name:
          - claude-code
          - copilot-cli
        update_homebrew: yes

    - name: Install useful tools using homebrew
      community.general.homebrew:
        name:
          - age
          - aichat
          - aws-vault
          - azure-cli
          - bat # CLI cat alternative with highlights https://github.com/sharkdp/bat
          - btop # CLI alternatvie to top https://github.com/aristocratos/btop
          - buf
          - buku
          - csvkit
          - doctl
          - eza
          - fastfetch
          - fd # CLI find alternative https://github.com/sharkdp/fd
          - ffmpeg
          - fzf
          - gh
          - glow # CLI tool to render markdown files https://github.com/charmbracelet/glow
          - gnupg # CLI tool for GNU pricay guard to generate and manage secure keys https://www.gnupg.org
          - go-task # CLI make alternative, task runner, build tool https://taskfile.dev
          - grc # CLI to do generic colourisation https://github.com/garabik/grc
          - gron # CLI to make JSON grepable by turning every value to full path https://github.com/tomnomnom/gron
          - helm
          - hugo
          - hyperfine
          - jc # CLI tool to convert other CLI tools output to JSON https://github.com/kellyjonbrazil/jc
          - jless # TUI to view JSON files with the ability to fold and search https://github.com/PaulJuliusMartinez/jless
          - jq
          - k9s
          - kubectl
          - kubectx
          - lazydocker
          - lnav # advanced logfile navigator https://lnav.org
          - minikube
          - ollama
          - opencode
          - pandoc
          - pass # CLI password manager https://www.passwordstore.org
          - protobuf
          - ripgrep # CLI tool to search directory for regex pattern https://github.com/BurntSushi/ripgrep
          - sd
          - sops
          - sshs # ssh TUI interface https://github.com/quantumsheep/sshs
          - starship # cross-shell prompt enhancements https://starship.rs
          - television
          - tlrc
          - tmux
          - tmuxinator
          - tree-sitter-cli
          - vegeta # CLI load testing tool https://github.com/tsenart/vegeta
          - yazi
          - yq
          - zellij
          - zoxide
        state: latest
        update_homebrew: yes
