- name: Run devtools tasks
  tags:
    - devtools
  block:
    - name: Install useful tools using homebrew
      community.general.homebrew:
        name:
          - age
          - aws-vault
          - awscli
          - azure-cli
          - bat # CLI cat alternative with highlights https://github.com/sharkdp/bat
          - btop # CLI alternatvie to top https://github.com/aristocratos/btop
          - buku
          - circleci
          - dagger
          - direnv
          - eza
          - fd # CLI find alternative https://github.com/sharkdp/fd
          - ffmpeg
          - fzf
          # - glow # CLI tool to render markdown files https://github.com/charmbracelet/glow
          - gnupg # CLI tool for GNU pricay guard to generate and manage secure keys https://www.gnupg.org
          - go-task # CLI make alternative, task runner, build tool https://taskfile.dev
          - grc # CLI to do generic colourisation https://github.com/garabik/grc
          - gron # CLI to make JSON grepable by turning every value to full path https://github.com/tomnomnom/gron
          - grype # CLI vulnerability scanner for container images https://github.com/anchore/grype
          - hugo
          - hyperfine # CLI benchmarking tool
          - jc # CLI tool to convert other CLI tools output to JSON https://github.com/kellyjonbrazil/jc
          - jless # TUI to view JSON files with the ability to fold and search https://github.com/PaulJuliusMartinez/jless
          - lnav # advanced logfile navigator https://lnav.org
          - pass # CLI password manager https://www.passwordstore.org
          - protobuf
          - ripgrep # CLI tool to search directory for regex pattern https://github.com/BurntSushi/ripgrep
          - snyk-CLI
          - sshs # ssh TUI interface https://github.com/quantumsheep/sshs
          - starship # cross-shell prompt enhancements https://starship.rs
          - syft # CLI tool to generate SOBM (software bill of materials) for container images and file systems https://github.com/anchore/syft
          - tldr
          - vegeta # CLI load testing tool https://github.com/tsenart/vegeta
          - yazi
          - zoxide
        state: latest
    - name: Install useful tools using Cargo
      community.general.cargo:
        name:
          - sd # CLI sed alternative https://github.com/chmln/sd
    - name: Install tools for kubernetes
      community.general.homebrew:
        name:
          - kubectl
          - minikube
          - helm
          - k9s
        state: latest
    - name: Install tools for docker
      community.general.homebrew:
        name:
          - lazydocker
        state: latest
    - name: Install hashicorp tap
      community.general.homebrew_tap:
        name:
          - hashicorp/tap
    - name: Install terraform
      community.general.homebrew:
        name:
          - hashicorp/tap/terraform
        state: latest
    - name: Install Hashicorp CLI
      community.general.homebrew:
        name:
          - hashicorp/tap/hcp
        state: latest
    - name: Install databricks tap
      community.general.homebrew_tap:
        name:
          - databricks/tap
    - name: Install databricks CLI
      community.general.homebrew:
        name:
          - databricks/tap/databricks
        state: latest
    - name: Install Cloudflare tap
      community.general.homebrew_tap:
        name: cloudflare/cloudflare
    - name: Install Cloudflare terraforming
      community.general.homebrew:
        name: cloudflare/cloudflare/cf-terraforming
        state: latest
