- name: Run devtools tasks
  tags:
    - devtools
  block:
  - name: Install lazygit
    community.general.homebrew:
      name: lazygit
      state: latest

  - name: Install age
    community.general.homebrew:
      name: age
      state: latest

  - name: Install tldr
    community.general.homebrew:
      name: tldr
      state: latest

  - name: Install sshs
    community.general.homebrew:
      name: sshs
      state: latest

  - name: Add julien-cpsn/atac to Homebrew
    community.general.homebrew_tap:
      name: julien-cpsn/atac

  - name: Install atac
    community.general.homebrew:
      name: atac
      state: latest

  - name: Install fzf
    community.general.homebrew:
      name: fzf
      state: latest

  - name: Add necessary config of fzf to zsh
    ansible.builtin.blockinfile:
      state: present
      path: $HOME/.zshrc
      block: |
        source <(fzf --zsh)
      marker_begin: "START FZF CONFIG"
      marker_end: "END FZF CONFIG"

  - name: Source zsh
    shell: source $HOME/.zshrc
    args:
      executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu
