---
- name: Run devtools tasks
  tags:
    - devtools
  block:
    - name: Install useful tools
      community.general.homebrew:
        name:
          - age
          - awscli
          - aws-vault
          - bat
          - btop
          - buku
          - circleci
          - dagger
          - direnv
          - eza
          - fd
          - fzf
          - ffmpeg
          - glow
          - gnupg
          - grc
          - grype
          - go-task
          - hugo
          - lnav
          - pass
          - protobuf
          - sshs
          - snyk-cli
          - syft
          - starship
          - tldr
          - yazi
          - zoxide
        state: latest

    - name: Install tools for kubernetes
      community.general.homebrew:
        name:
          - kubectl
          - minikube
          - helm
        state: latest

    - name: Install tools for docker
      community.general.homebrew:
        name:
          - lazydocker
        state: latest

    - name: Install hashicorp tap
      community.general.homebrew_tap:
        name:
          - hashicorp/tap

    - name: Install terraform
      community.general.homebrew:
        name:
          - hashicorp/tap/terraform
        state: latest

    - name: Install databricks tap
      community.general.homebrew_tap:
        name:
          - databricks/tap

    - name: Install databricks cli
      community.general.homebrew:
        name:
          - databricks/tap/databricks
        state: latest
    # - name: Install hashicorp terraform
    #   ansible.builtin.shell: |
    #     brew tap hashicorp/tap
    #     brew install hashicorp/tap/terraform
