- name: Install fontconfig
  ansible.builtin.apt:
    name: fontconfig
    state: present

- name: Ensure fonts directory exits
  file:
    path: $HOME/.local/share/fonts
    state: directory

- name: Install JetBrains fonts
  ansible.builtin.shell: |
    wget -P $HOME/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip && \
    cd $HOME/.local/share/fonts && \
    unzip JetBrainsMono.zip && \
    rm JetBrainsMono.zip && \
    fc-cache -fv
