- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Setup Git email
  git_config:
    name: user.email
    scope: global
    value: "{{ github_email }}"
  become_user: "{{ user }}"

- name: Setup Git name
  git_config:
    name: user.name
    scope: global
    value: "{{ github_name }}"
  become_user: "{{ user }}"