- name: Run git tasks
  tags:
    - git
  block:
    - name: Install git
      community.general.homebrew:
        name:
          - git
          - lazygit
          - git-delta
        state: latest

    - name: Render gitconfig
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/gitconfig.j2"
        dest: "{{ ansible_env.HOME }}/.gitconfig"
        backup: yes

    - name: Ensure ~/projects/work directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/projects/work"
        state: directory
