- name: Run harlequin tasks
  tags:
    - harlequin
  block:
  - name: Install pipx
    community.general.homebrew:
      name: pipx
      state: present

  - name: Install harlequin
    community.general.pipx:
      name: harlequin
      state: present
