- name: Run neovim tasks
  tags:
    - neovim
  block:
    - name: Install neovim dependencies
      community.general.homebrew:
        name:
          - chafa
          - gcc
          - git
          - llvm
          - ripgrep
          - unzip
          - viu
          - xclip
        state: latest

    - name: Install neovim
      community.general.homebrew:
        name: neovim
        state: latest

    - name: Delete backup directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - $HOME/.local/share/nvim.bak
        - $HOME/.local/state/nvim.bak
        - $HOME/.cache/nvim.bak

    - name: Move last version of state, share and cache files to backup
      ansible.builtin.shell: |
        if [ -d $HOME/.local/share/nvim ]; then mv $HOME/.local/share/nvim $HOME/.local/share/nvim.bak; else echo "No need to copy"; fi
        if [ -d $HOME/.local/state/nvim ]; then mv $HOME/.local/state/nvim $HOME/.local/state/nvim.bak; else echo "No need to copy"; fi
        if [ -d $HOME/.cache/nvim ]; then mv $HOME/.cache/nvim $HOME/.cache/nvim.bak; else echo "No need to copy"; fi
