---
- name: Run nodejs tasks
  tags:
    - nodejs
  block:
    - name: Install bash
      community.general.homebrew:
        name: bash
        state: latest

    - name: Install nvm
      ansible.builtin.shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
      args:
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Install different nodejs versions
      ansible.builtin.shell: |
        . $HOME/.nvm/nvm.sh && nvm install {{ item }}
      args:
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/{{ item }}"
      loop:
        - 10.24.1
        - 14.21.3
        - 16.20.2
        - 18.20.7
        - 20.18.3
        - 22.14.0
