- name: Run notes tasks
  tags:
    - notes
  block:
    - name: Clone personal notes from public GitHub repository
      ansible.builtin.git:
        repo: git@github.com:GabrielDCelery/personal-notes.git
        dest: $HOME/notes
        version: master
        update: yes
        clone: yes

