
- name: Run notes tasks
  tags:
    - notes
  block:
  - name: Clone personal notes from public GitHub repository
    ansible.builtin.git:
      repo: git@github.com:GabrielDCelery/personal-notes.git
      dest: $HOME/notes
      version: master
      update: yes
      clone: yes

  - name: Configure personal notes
    ansible.builtin.blockinfile:
      state: present
      path: $HOME/.zshrc
      block: |
        export PERSONAL_NOTES_INBOX_DIR=$HOME/notes/inbox
        export PERSONAL_NOTES_TEMPLATE=$HOME/notes/templates/default.md
        export PERSONAL_NOTES_DEFAULT_AUTHOR={{ personal_notes_author }}
      marker_begin: "START PERSONAL NOTES CONFIG"
      marker_end: "END PERSONAL NOTES CONFIG"

  - name: Source zsh
    shell: source $HOME/.zshrc
    args:
      executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu

