- name: Run programming languages task
  tags:
    - programminglanguages
  block:
    - name: Install mise
      community.general.homebrew:
        name:
          - mise
    - name: Install programming languages specified in global mise.toml
      ansible.builtin.shell: |
        mise trust
        mise install
