- name: Download starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'
  register: starship_install_script
  become_user: "{{ user }}"

- name: Install starship
  ansible.builtin.shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh
  when: starship_install_script.changed
  become_user: "{{ user }}"

- name: Check if zshrc has the starship configuration
  lineinfile:
    state: absent
    path: ~/.zshrc
    regexp: eval "$(starship init zsh)"
  check_mode: true
  changed_when: false # This just makes things look prettier in the logs
  register: check
  become_user: "{{ user }}"

- name: Add starship to zshrc if does not exist
  lineinfile:
    state: present
    path: ~/.zshrc
    line: eval "$(starship init zsh)"
  when: check.found == 0
  become_user: "{{ user }}"

- name: Source zsh
  shell: source ~/.zshrc
  args:
    executable: /usr/bin/zsh
  when: check.found == 0
  become_user: "{{ user }}"
