- name: Run starship tasks
  tags:
    - starship
  block:
  - name: Install starship
    community.general.homebrew:
      name: starship
      state: present

  - name: Add starship init script to zshrc if not present
    ansible.builtin.blockinfile:
      state: present
      path: $HOME/.zshrc
      block: |
        eval "$(starship init zsh)"
      marker_begin: "STARSHIP CONFIG"
      marker_end: "STARSHIP CONFIG"

  - name: Source zsh
    shell: source $HOME/.zshrc
    args:
      executable: /bin/zsh # needs to be /usr/bin/zsh on ubuntu
