- name: Install stow
  community.general.homebrew:
    name: stow
    state: present

- name: Create .config directory if does not exist
  file:
    path: $HOME/.config
    state: directory
  become_user: "{{ user }}"

- name: Clone personal dotfiles from public GitHub repository
  ansible.builtin.git:
    repo: git@github.com:GabrielDCelery/personal-dotfiles.git
    dest: $HOME/.dotfiles
    version: main
    update: yes
    clone: yes
  become_user: "{{ user }}"

#- name: Install tmux plugins (TODO - this is a hack because for some reason the tmux plugins don't get installed)
#  ansible.builtin.shell: $HOME/.dotfiles/.tmux/plugins/tpm/scripts/install_plugins.sh
#  become_user: "{{ user }}"

- name: Stow $HOME/.dotfiles
  ansible.builtin.shell: stow --dir=$HOME/.dotfiles .
  become_user: "{{ user }}"

  
