- name: Install stow
  ansible.builtin.apt:
    name: stow
    state: present

- name: Create .config directory if does not exist
  file:
    path: ~/.config
    state: directory
  become_user: "{{ user }}"

- name: Clone personal dotfiles from public GitHub repository
  ansible.builtin.git:
    repo: git@github.com:GabrielDCelery/personal-dotfiles.git
    dest: $HOME/.dotfiles
    version: main
    update: yes
    clone: yes
  become_user: "{{ user }}"

- name: Stow ~/.dotfiles
  ansible.builtin.shell: stow --dir=$HOME/.dotfiles .
  become_user: "{{ user }}"

  