---
- name: Run zsh
  tags:
    - zsh
  block:
    - name: Install oh my zsh if not present
      ansible.builtin.shell: |
        [ -d  $HOME//.oh-my-zsh ] || yes 'Y' | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Install zsh related tools
      community.general.homebrew:
        name:
          - zsh-autosuggestions
          - zsh-syntax-highlighting
        state: latest

    - name: Source .zshrc.personal file
      ansible.builtin.blockinfile:
        state: present
        path: $HOME/.zshrc
        block: |
          if [ -e "$HOME/.zshrc.personal" ]; then
            source $HOME/.zshrc.personal
          fi
        marker_begin: "START PERSONAL ZSH CONFIG"
        marker_end: "END PERSONAL ZSH CONFIG"

    - name: Source .zshrc.personal file
      ansible.builtin.blockinfile:
        state: present
        path: $HOME/.zshrc
        block: |
          if [ -e "$HOME/.zshrc.custom" ]; then
            source $HOME/.zshrc.custom
          fi
        marker_begin: "START CUSTOM ZSH CONFIG"
        marker_end: "END CUSTOM ZSH CONFIG"
