- name: Run zsh
  tags:
    - zsh
  block:
    - name: Ensure zsh plugins directory exists
      file:
        path: $HOME/.zsh/plugins
        state: directory

    - name: Install zsh-completions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-completions.git
        dest: $HOME/.zsh/plugins/zsh-completions
        version: 0.35.0
        force: true
        update: false

    - name: Install fzf-tab
      ansible.builtin.git:
        repo: https://github.com/Aloxaf/fzf-tab.git
        dest: $HOME/.zsh/plugins/fzf-tab
        version: v1.2.0
        force: true
        update: false

    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: yes

    - name: Install zsh-autosuggestions
      community.general.homebrew:
        name:
          - zsh-autosuggestions
        state: latest

    - name: Install zsh-syntax-highlighting
      community.general.homebrew:
        name:
          - zsh-syntax-highlighting
        state: latest

    - name: Add .zshrc.personal file
      ansible.builtin.blockinfile:
        state: present
        path: $HOME/.zshrc
        block: |
          if [ -e "$HOME/.zshrc.personal" ]; then
            source $HOME/.zshrc.personal
          fi
        marker_begin: "START PERSONAL ZSH CONFIG"
        marker_end: "END PERSONAL ZSH CONFIG"

    - name: Add .zshrc.custom file
      ansible.builtin.blockinfile:
        state: present
        path: $HOME/.zshrc
        block: |
          if [ -e "$HOME/.zshrc.custom" ]; then
            source $HOME/.zshrc.custom
          fi
        marker_begin: "START CUSTOM ZSH CONFIG"
        marker_end: "END CUSTOM ZSH CONFIG"

    - name: Source .zshrc
      ansible.builtin.shell: |
        /bin/bash $HOME/.zshrc
